// Gabriel Seethor, A0257008H (Whole File)
import React from 'react';
import { render, screen, act, waitFor, fireEvent} from '@testing-library/react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import axios from 'axios';
import ProductDetails from '../pages/ProductDetails';


//Generated by AI To Serve as a teaching point/tutorial for learning 
//Attribution: This file is prepared with the help of DeepSeek-V3.2

// Mock axios
jest.mock('axios');

// Mock context hooks
jest.mock('../context/auth', () => ({
  useAuth: jest.fn(() => [null, jest.fn()])
}));

jest.mock('../context/cart', () => ({
  useCart: jest.fn(() => [null, jest.fn()])
}));

jest.mock('../context/search', () => ({
  useSearch: jest.fn(() => [{ keyword: '' }, jest.fn()])
}));


jest.mock('../hooks/useCategory', () => ({
  __esModule: true,
  default: jest.fn(() => [[
    { _id: 'cat1', name: 'Electronics', slug: 'electronics' },
    { _id: 'cat2', name: 'Books', slug: 'books' },
    { _id: 'cat3', name: 'Clothing', slug: 'clothing' }
  ], jest.fn()])
}));

describe('Product Details Component', () => {
  const mockProduct = {
    _id: '123',
    name: 'Test Product',
    description: 'Test Description',
    price: 100,
    category: { _id: 'cat1', name: 'Electronics' },
    slug: 'test-product'
  };

  const mockSimilarProduct = {

    _id: '456',
    name: 'Similar Product',
    description: 'Similar Description',
    price: 150,
    category: { _id: 'cat1', name: 'Electronics' },
    slug: 'similar-product'
  }

  const mockSimilarProducts = [
    {
      _id: '456',
      name: 'Similar Product',
      description: 'Similar Description',
      price: 150,
      category: { _id: 'cat1', name: 'Electronics' },
      slug: 'similar-product'
    } , 
     {
      _id: '457',
      name: 'Another Similar Product',
      description: 'Another Similar Description',
      price: 200,
      category: { _id: 'cat1', name: 'Electronics' },
      slug: 'another-similar-product'
    }
  ];

  const emptyMockSimilarProducts = [];

  beforeEach(() => {
    jest.clearAllMocks();
  })



it('recommended products render accordingly', async () => {
    
    axios.get
      .mockImplementation((url) => {
        if (url.includes('/api/v1/product/get-product/')) {
          return Promise.resolve({
            data: {
              product: mockProduct,
              success: true
            }
          });
        }
        if (url.includes('/api/v1/category/get-category')) {
          return Promise.resolve({
            data: { category: [] }
          });
        }
        if (url.includes('/api/v1/product/related-product/')) {
          return Promise.resolve({
            data: { products: mockSimilarProducts }
          });
        }
        return Promise.reject(new Error('Not mocked'));
      });

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/product/test-product']}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>
      );
    });

    
    const similarProduct = await screen.findByText('Similar Product');
    expect(similarProduct).toBeInTheDocument();
  
    const anotherSimilarProduct = screen.queryByText('Another Similar Product');
    expect(anotherSimilarProduct).toBeInTheDocument();
  
     

});

it('if there are no products, show "No Similar Products"', async () => {
    
    axios.get
      .mockImplementation((url) => {
        if (url.includes('/api/v1/product/get-product/')) {
          return Promise.resolve({
            data: {
              product: mockProduct,
              success: true
            }
          });
        }
        if (url.includes('/api/v1/category/get-category')) {
          return Promise.resolve({
            data: { category: [] }
          });
        }
        if (url.includes('/api/v1/product/related-product/')) {
          return Promise.resolve({
            data: { products: emptyMockSimilarProducts }
          });
        }
        return Promise.reject(new Error('Not mocked'));
      });

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/product/test-product']}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>
      );
    });


    const similarProduct = await screen.findByText(/No Similar Products/);
    expect(similarProduct).toBeInTheDocument();
  
    
  
     

});
it('clicking on one of the similar products navigates to the product page', async () => {
    
    axios.get
      .mockImplementation((url) => {
        if (url.includes('/api/v1/product/get-product/')) {


          const slug = url.split('/api/v1/product/get-product/')[1];

          if (slug === "test-product") {
          return Promise.resolve({
            data: {
              product: mockProduct,
              success: true
            }
          })
          } else if (slug === "similar-product") {
            return Promise.resolve({
              data: {
                product: mockSimilarProduct,
                success: true
              }
            })
          } else {
            return Promise.reject(new Error('Product not found'));
          }
        }
        if (url.includes('/api/v1/category/get-category')) {
          return Promise.resolve({
            data: { category: [] }
          });
        }
        if (url.includes('/api/v1/product/related-product/')) {
          return Promise.resolve({
            data: { products: mockSimilarProducts }
          });
        }
        return Promise.reject(new Error('Not mocked'));
      });

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/product/test-product']}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>
      );
    });

     
     const similarProduct = await screen.findByText('Similar Product');

     const moreDetailsButtons = screen.getAllByText('More Details');
     fireEvent.click(moreDetailsButtons[0]);

      await waitFor( () => {
            expect(screen.getByText('Product Details')).toBeInTheDocument();
            expect(screen.getByText(/Name : Similar Product/)).toBeInTheDocument();
            expect(screen.getByText(/Description : Similar Description/)).toBeInTheDocument();
             expect(screen.getByText(/Price : \$150.00/)).toBeInTheDocument();



      })




  
  
    
  
     

});

});